### ISSUE TITLE
Unable to replicate figures from paper using Tablefig.r

### ISSUE THREAD

**Issue by jovan-stojanovic** [rainfireliang/TwitterDiffusionData#1]
Hi @rainfireliang, thanks for sharing the code from the paper, very interesting method and results.
I have an issue reproducing them with the R script Tablefig.r: [I get `object 'fm_t'` in not found`` here.](https://github.com/rainfireliang/TwitterDiffusionData/blob/d484eb3ac96ad7a993c8e9fbebeac2bda27ad8b3/TableFig.r#L11)

Indeed, it seems that the results from the multilevel logistic regression model are missing, and this is affecting the generation of subsequent plots.
Also, the data that were loaded using `load("data_model.Rdata")` are not used.

Do you think this could be solved? Thanks!

**Comment by rainfireliang** [comment]
I just realized that the file is too large, and I failed to upload the correct file on Github! Thanks a lot! Now you can download the Rdata file here: https://www.dropbox.com/scl/fi/zzrodbwllzpqihpcxs3ul/data_model.RData?rlkey=47p11nynuu1xxe7edzk7v5190&dl=0. I will try to upload on GitHub later.

**Comment by jovan-stojanovic** [comment]
Oh I see, thanks! Closing this issue. 
Maybe the easiest way for you to do this is just to put a comment at the beginning of the file with the link to this dropbox file? Seems enough.
